console.log("Rodando o sistema de gerenciamento de jogos, só que não")
console.log("Aplicação esta se conectando ao banco de dados")
console.log("Ver a alteração no git pull")
console.log("terceira alteração para o push")
console.log("nova alteração para o pull")
